version: '3.8'
services:
  api:
    build: .
    ports:
      - "5079:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=kaosnetdb;User=root;Password=clave123;
    depends_on:
      - db

  db:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: clave123
      MYSQL_DATABASE: kaosnetdb
    ports:
      - "3306:3306"
