name: CI/CD KaosNet Backend

on:
  push:
    branches:
      - '**'  
  pull_request:
    branches:
      - '**'
  release:
    types: [created]

jobs:
  build-and-test:
    name: Build and Validate Project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Run tests (si tienes)
      run: dotnet test || echo "No tests found"

  docker-publish:
    name: Build and Push Docker Image
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'release'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          jeaninformatico/kaosnet-backend:latest
          jeaninformatico/kaosnet-backend:${{ github.sha }}
          ${{ github.event.release.tag_name && format('jeaninformatico/kaosnet-backend:{0}', github.event.release.tag_name) || '' }}
