name: publish

on:
  release:
    types:
      - created

jobs:
  check-docker-secrets:
    name: Check Docker Secrets
    runs-on: ubuntu-latest
    outputs:
      is_have_secrets: ${{ steps.check_secret_job.outputs.is_have_secrets }}
    steps:
      - id: check_secret_job
        run: |
          if [[ "${{ vars.DOCKER_REPO }}" != "" && \
                "${{ secrets.DOCKER_USERNAME }}" != "" && \
                "${{ secrets.DOCKER_TOKEN }}" != "" ]]; \
          then
            echo "is_have_secrets=true" >> $GITHUB_OUTPUT
          else
            echo "is_have_secrets=false" >> $GITHUB_OUTPUT
          fi

  push-docker-image:
    name: Push Docker Image
    needs: check-docker-secrets
    if: needs.check-docker-secrets.outputs.is_have_secrets == 'true'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6.2.0
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ${{ vars.DOCKER_REPO }}:latest
          ${{ vars.DOCKER_REPO }}:${{ github.event.release.tag_name }}
